name: build

on:
  push:
    branches:
      - stable
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up environment & Build
        run: |
          bash build.sh c
        env:
          PAT: ${{ secrets.PAT }} # Diteruskan ke script jika script membutuhkan token

      - name: Upload Kernel Artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.KERNELZIP }}
          tag_name: v1.0.${{ github.run_number }} # Tag dinamis agar tidak bentrok
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }} # PAT digunakan sebagai token upload
